name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
            | docker login --username AWS \
            --password-stdin 335877214259.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ecommerce-app:$IMAGE_TAG .

      - name: Tag Docker image
        run: |
          docker tag ecommerce-app:$IMAGE_TAG \
            335877214259.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-app:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          docker push 335877214259.dkr.ecr.ap-south-1.amazonaws.com/ecommerce-app:$IMAGE_TAG

      - name: Force ECS service redeploy
        run: |
          aws ecs update-service \
            --cluster ecommerce-cluster \
            --service ecommerce-service \
            --task-definition ecommerce-task:latest \
            --force-new-deployment
